version: '2'

services:

  eventstore:
    build:
      context: ./build
      args:
        ES_VERSION: 3.9.0
    volumes:
      - "./data/eventstore:/var/lib/eventstore"
    ports:
     - "2113:2113"
     - "1113:1113"