version: '3'

services:
  eventstore:
      image: "eventstore/eventstore:latest"
      volumes:
          - "./data/eventstore:/var/lib/eventstore"
      ports:
          - "2113:2113"
          - "1113:1113"
